---
- hosts: all
  gather_facts: yes
  sudo: true

  tasks:
    - include: tasks/java.yml
      tags:
        - Java
        - Dependencies
        - Install

    - name: Locomotive | Add Locomotive Group
      group:
        name: locomotive

    - name: Locomotive | Add Locomotive User
      user:
        name: locomotive
        group: locomotive
        system: yes
      tags:
        - Install

    - name: Locomotive | Setup Locomotive Directory
      file:
        path: /usr/local/locomotive/
        state: directory
        owner: locomotive
        group: locomotive
      tags:
        - Install

- hosts: locomotive-local
  gather_facts: yes
  sudo: true

  tasks:
    - include: tasks/postgres.yml
      tags:
        - Postgres
        - Install

- hosts: all
  gather_facts: yes
  sudo: true

  tasks:
    - name: Locomotive | Detect Locomotive Version
      local_action: shell sed -rn 's/.*<locomotive\.version>(.*)<\/locomotive\.version>/\1/p' ../pom.xml
      register: locomotive_version
      tags:
        - Install
        - Deploy

    - name: Locomotive | Locomotive Version Output
      debug: "msg='Provisioning Locomotive Version: {{ locomotive_version.stdout }}'"

    - name: Locomotive | Link Locomotive JAR as Service
      file:
        src: /usr/local/locomotive/target/locomotive-{{ locomotive_version.stdout }}.jar
        dest: /etc/init.d/locomotive
        state: link
        mode: 0755
      tags:
        - Install
        - Deploy

    - name: Locomotive | Setup Locomotive to Start on Boot
      command: 'update-rc.d locomotive defaults'
      tags:
        - Install
        - Deploy

    - name: Locomotive | Restart Locomotive Service
      service:
        name: locomotive
        state: restarted
        enabled: yes
      tags:
        - Deploy
        - Restart